[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
flow_testnet = "https://testnet.evm.nodes.onflow.org"
flow_mainnet = "https://mainnet.evm.nodes.onflow.org"
